# Generated by Django 4.2 on 2026-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbs_per_100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Углеводы на 100г'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Жиры на 100г'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Белки на 100г'),
        ),
    ]
